services:
  web:
    build:
      context: frontend
      dockerfile: Dockerfile
      args:
        - REACT_APP_API_URL=$REACT_APP_API_URL
    ports:
      - 3000:3000

  server:
    build:
      context: backend
      dockerfile: Dockerfile
      args:
        - GMAIL_USERNAME=$GMAIL_USERNAME
        - GMAIL_PASS=$GMAIL_PASS
        - PORT=$PORT
    ports:
      - 3001:3001
